### ISSUE TITLE
wagon serve can be start different rake server than Thin

### ISSUE THREAD

**Issue by joel** [locomotivecms/wagon#193]
For the moment `wagon serve` can only start Thin rack server, but it should be can running another one like Puma, Webrick, and so on.

**Comment by ahmgeek** [comment]
@did actually I am facing a hanging process with `bundle exec wagon serve` right now.
**warning** I'll put the stack trace:
```
	from /home/ahmgeek/.rbenv/versions/2.3.0/bin/wagon:23:in `<main>'
	from /home/ahmgeek/.rbenv/versions/2.3.0/bin/wagon:23:in `load'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.0.0/bin/wagon:12:in `<top (required)>'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon/cli.rb:277:in `serve'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon.rb:39:in `serve'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon/commands/serve_command.rb:14:in `start'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.0.0/lib/locomotive/wagon/commands/serve_command.rb:35:in `start'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run'
	from /home/ahmgeek/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/eventmachine-1.0.9.1/lib/eventmachine.rb:193:in `run_machine'
```

**Comment by ahmgeek** [comment]
I've put it here, as I though it's related to `thin`
