### ISSUE TITLE
Devise error preventing server from starting

### ISSUE THREAD

**Issue by jimzar** [locomotivecms/wagon#216]
The error message is the following:

``` Shell
Digest::Digest is deprecated; use Digest
E, [2014-10-28T20:09:59.276235 #28106] ERROR -- : undefined method `secret_key=' for Devise:Module (NoMethodError)
/Users/jimzar/Sites/acme_cms/config/initializers/devise.rb:4:in `block in <top (required)>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/devise-2.2.7/lib/devise.rb:267:in `setup'
/Users/jimzar/Sites/acme_cms/config/initializers/devise.rb:3:in `<top (required)>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `block in load'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:236:in `load_dependency'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/activesupport-3.2.19/lib/active_support/dependencies.rb:245:in `load'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/engine.rb:593:in `block (2 levels) in <class:Engine>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/engine.rb:592:in `each'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/engine.rb:592:in `block in <class:Engine>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `instance_exec'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/initializable.rb:30:in `run'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/initializable.rb:55:in `block in run_initializers'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `each'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/initializable.rb:54:in `run_initializers'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/application.rb:136:in `initialize!'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/railties-3.2.19/lib/rails/railtie/configurable.rb:30:in `method_missing'
/Users/jimzar/Sites/acme_cms/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/rack-1.4.5/lib/rack/builder.rb:51:in `instance_eval'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/rack-1.4.5/lib/rack/builder.rb:51:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `eval'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn.rb:48:in `block in builder'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `call'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/bin/unicorn_rails:139:in `block in rails_builder'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `call'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:764:in `build_app!'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:628:in `init_worker_process'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:651:in `worker_loop'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:140:in `start'
/Users/jimzar/.rvm/gems/ruby-2.1.3/gems/unicorn-4.8.3/bin/unicorn_rails:209:in `<top (required)>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/bin/unicorn_rails:23:in `load'
/Users/jimzar/.rvm/gems/ruby-2.1.3/bin/unicorn_rails:23:in `<main>'
/Users/jimzar/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/Users/jimzar/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `<main>'
```

When I comment the following lines in devise.rb it works for some reason.

``` ruby
config.secret_key = "d9eb5171c59a4c817f68b0de27b8c1e340c2341b52cdbc60d3083d4e8958532" \
                      "18dcc5f589cafde048faec956b61f864b9b5513ff9ce29bf9e5d58b0f234f8e3b"
```

**Comment by justinhillsjohnson** [comment]
@mkempe I'm getting the error, as well. Here my `Gemfile.lock`:

```
    devise (2.2.7)
      bcrypt-ruby (~> 3.0)
      orm_adapter (~> 0.1)
      railties (~> 3.1)
      warden (~> 1.2.1)
    devise-encryptable (0.1.2)
      devise (>= 2.1.0)
```

**Comment by wulffeld** [comment]
@mkempe Same problem. Followed the get started instructions to a tee (I think :).

I don't think secret_key is available until Devise 3 but not entirely sure.

**Comment by mkempe** [comment]
Hey there,

@wulffeld is right, the line `config.secret_key` in the generated devise initializers creates the problem.

Could you please run `rails g devise:install` in your engine, aka Rails project, to get an updated version.

@did / @gregory Should we remove the line from the template in the `v2.5.x` branch.

**Comment by gregory** [comment]
Or we could just use the [devise generator](https://github.com/plataformatec/devise/blob/a76dfd655228e7b540ed3761f9ebc7b96f96418c/lib/generators/devise/devise_generator.rb) to generate on the config file on the fly?

**Comment by justinhillsjohnson** [comment]
@mkempe I ran `$ rails g devise:install` and this was the error I got:

```/Users/justin/cms/config/initializers/devise.rb:4:in `block in <top (required)>': undefined method `secret_key=' for Devise:Module (NoMethodError)```

**Comment by mkempe** [comment]
Sorry, unfortunately forgot to say that you have to delete the generated device initializer:

```
$ rm /Users/justin/cms/config/initializers/devise.rb
```

**Comment by mkempe** [comment]
PS: If you should have problems with the installation, maybe you can checkout LocoRoco, a ready to deploy LocomotiveCMS package, which i build: https://bitaculous.github.io/locoroco/

**Comment by did** [comment]
FYI guys, I've modified the generated devise file in the v2.5.x branch of the engine:
https://github.com/locomotivecms/engine/commit/129f29d418d5314530e766736d541443e52d6f27

**Comment by burabure** [comment]
installed engine according to this tut http://doc.locomotivecms.com/get-started/install-engine-locally#linux. got the same error. solved by deleting devise.rb and running rails g devise:install

so i guess the fix isn't working

ubuntu 14.04

**Comment by nickrttn** [comment]
I'm getting the same error on Mavericks, fresh install of Ruby 2.0.0 and Rails 3.2.19.

**Comment by ondenman** [comment]
Same under El Capitan. Rails 3.2.19. Ruby 2.1.4p265
