### ISSUE TITLE
wagon generate page fails

### ISSUE THREAD

**Issue by paulbaker3** [locomotivecms/wagon#228]
When running `wagon generate page foo` from a LocomotiveCMS directory results in the following error: 

```
Sun Feb 08 00:25:58 ~/Projects/wagon/foosite
[10066] $ wagon generate page foo
/Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon.rb:140:in `generate': uninitialized constant Locomotive::Wagon::Bundler (NameError)
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/cli.rb:130:in `page'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/lib/ruby/gems/1.9.1/gems/locomotivecms_wagon-1.5.2/bin/wagon:12:in `<top (required)>'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/bin/wagon:23:in `load'
	from /Users/paulbaker/.rbenv/versions/1.9.3-p484/bin/wagon:23:in `<main>'
```

I am able to successfully serve my site locally, but I am unable to create new artifacts using the wagon tool.

**Comment by did** [comment]
use ````bundle wagon generate page foo```` instead.
