### ISSUE TITLE
superclass mismatch for class MemoryAdapter

### ISSUE THREAD

**Issue by KazW** [locomotivecms/wagon#254]
When pushing/deploying to any configured engine, I get the following error:
```superclass mismatch for class MemoryAdapter```
I'm using MRI 2.2.2 and wagon 2.0.0-beta.2. I'm new to Locomotive, is there any wagon option to get a full stacktrace?

**Comment by did** [comment]
hi @KazW. try the "-v" option when deploying your site. Btw, which version of the engine did you test the deployment? One last thing, could you try with one of the latest commits of Wagon?
thanks!

**Comment by KazW** [comment]
Here are the versions I'm using:
Engine: 35c4faf
Steam: f5c23e0
Wagon: 2b9285c
They should all be the latest masters.

Wagon output with -v:
```superclass mismatch for class MemoryAdapter
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/adapters/memory.rb:9:in '<module:Steam>'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/adapters/memory.rb:7:in '<top (required)>'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/adapters/filesystem.rb:1:in 'require_relative'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/adapters/filesystem.rb:1:in '<top (required)>'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/repositories.rb:44:in 'require_relative'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/repositories.rb:44:in 'build_adapter'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/repositories.rb:11:in 'block in <class:Repositories>'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/morphine-0.1.1/lib/morphine.rb:15:in 'instance_exec'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/morphine-0.1.1/lib/morphine.rb:15:in 'block in register'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_steam-1.0.0.pre.beta.3/lib/locomotive/steam/repositories.rb:15:in 'block in <class:Repositories>'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/morphine-0.1.1/lib/morphine.rb:15:in 'instance_exec'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/morphine-0.1.1/lib/morphine.rb:15:in 'block in register'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/concerns/steam_concern.rb:18:in 'block in steam_services'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/concerns/steam_concern.rb:16:in 'tap'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/concerns/steam_concern.rb:16:in 'steam_services'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:37:in 'push'
  /usr/local/Cellar/rbenv/0.4.0/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:29:in 'push'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon.rb:73:in 'push'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/cli.rb:313:in 'deploy'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in 'dispatch'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
  /usr/local/opt/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/bin/wagon:12:in '<top (required)>'
  /usr/local/opt/rbenv/versions/2.2.2/bin/wagon:23:in 'load'
  /usr/local/opt/rbenv/versions/2.2.2/bin/wagon:23:in '<main>'```

**Comment by did** [comment]
thanks @KazW. I appreciate. 
One last thing, could you send me the source of the Wagon site you were trying to deploy?
In the meantime, I'm going to install ruby 2.2.2 on my machine.

**Comment by did** [comment]
works fine on my machine running ruby 2.2.2.

**Comment by KazW** [comment]
The site was a new one generated with ```wagon init``` and one was a clone from a new site, there was no custom code written, the link below is from the clone. Thanks for your help so far, this seems to be a strange issue.

https://github.com/KazW/test-blog

**Comment by did** [comment]
thanks @KazW but it worked fine on my machine:
````
/tmp/test-blog[master] > ruby -v
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
/tmp/test-blog[master] > bundle exec wagon deploy production -v

Pushing Site
  persisting Test Blog [skip]

Pushing ContentTypes

Pushing Pages
  persisting index (en) [done]
  persisting 404 (en) [done]

Pushing Snippets

Pushing ThemeAssets
````
