### ISSUE TITLE
pushing multilingual pages fails (2.0.0.pre.beta.2)

### ISSUE THREAD

**Issue by rryter** [locomotivecms/wagon#260]
I created a new site running on `gem 'locomotivecms', '~> 3.0.0.pre.beta.1'`, added the languages `fr, it and de` in the backoffice, saved and then pulled the page with `bundle exec wagon pull development -r pages --verbose`. Then, without modifying the page at all I tried to do a `bundle exec wagon push development -r pages --verbose` which results in the following error:
```
persisting index (de, fr, it, en)error
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.pre.beta.2/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.pre.beta.2/lib/locomotive/coal/resources/concerns/request.rb:7:in `get'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_coal-1.0.0.pre.beta.2/lib/locomotive/coal/resources/pages.rb:15:in `fullpaths'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:53:in `block in remote_entities'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:52:in `tap'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:52:in `remote_entities'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:46:in `remote_entity_id'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:18:in `persist'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:32:in `block in _push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:28:in `each'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:28:in `_push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:23:in `block in _push_with_timezone'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:22:in `_push_with_timezone'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `block in push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:44:in `instrument'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:14:in `push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:10:in `push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:40:in `block in push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:54:in `block in each_resource'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:47:in `each'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:47:in `each_resource'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:39:in `push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/commands/push_command.rb:29:in `push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon.rb:73:in `push'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/lib/locomotive/wagon/cli.rb:313:in `deploy'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/rryter/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.pre.beta.2/bin/wagon:12:in `<top (required)>'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/bin/wagon:23:in `load'
	/Users/rryter/.rbenv/versions/2.2.1/gemsets/locomotive/bin/wagon:23:in `<main>'
```

Error on the engine:
```
Started GET "/locomotive/api/v3/pages/fullpaths.json?auth_token=vCFmdMeGWBTEsdpPdzJN" for ::1 at 2015-09-22 10:58:40 +0200
[LocomotiveCMS] [fetch site] host = localhost / site_handle = "parched-winter-1025"
  MOPED: 127.0.0.1:27017 COMMAND      database=admin command={:ismaster=>1} runtime: 0.3730ms
  MOPED: 127.0.0.1:27017 QUERY        database=locomotive-dev collection=locomotive_sites selector={"$query"=>{"handle"=>"parched-winter-1025"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.4190ms
  MOPED: 127.0.0.1:27017 QUERY        database=locomotive-dev collection=locomotive_accounts selector={"$query"=>{"email"=>"reto.ryter@twygmbh.ch", "authentication_token"=>"vCFmdMeGWBTEsdpPdzJN"}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.4140ms
  MOPED: 127.0.0.1:27017 QUERY        database=locomotive-dev collection=locomotive_accounts selector={"$query"=>{"_id"=>BSON::ObjectId('5592e7e2746facb3740010e9')}, "$orderby"=>{:_id=>1}} flags=[] limit=-1 skip=0 batch_size=nil fields=nil runtime: 0.2950ms
  MOPED: 127.0.0.1:27017 QUERY        database=locomotive-dev collection=locomotive_pages selector={"$query"=>{"site_id"=>BSON::ObjectId('56010d36bcd8d46a02000000')}, "$orderby"=>{"position"=>1}} flags=[] limit=0 skip=0 batch_size=nil fields={"_id"=>1, "fullpath.de"=>1} runtime: 0.8670ms

ActiveModel::MissingAttributeError - Missing attribute: 'fullpath'.:
  mongoid (4.0.2) lib/mongoid/attributes.rb:97:in `read_attribute'
  mongoid (4.0.2) lib/mongoid/fields.rb:409:in `block (2 levels) in create_field_getter'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:562:in `delegate_attribute'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:551:in `value_for'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:464:in `block in serializable_hash'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:462:in `each'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:462:in `inject'
  grape-entity (0.4.5) lib/grape_entity/entity.rb:462:in `serializable_hash'
  activesupport (4.2.4) lib/active_support/core_ext/object/json.rb:140:in `block in as_json'
  activesupport (4.2.4) lib/active_support/core_ext/object/json.rb:140:in `map'
  activesupport (4.2.4) lib/active_support/core_ext/object/json.rb:140:in `as_json'
  activesupport (4.2.4) lib/active_support/json/encoding.rb:35:in `encode'
  activesupport (4.2.4) lib/active_support/json/encoding.rb:22:in `encode'
  activesupport (4.2.4) lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
  grape (0.12.0) lib/grape/formatter/json.rb:6:in `call'
  grape (0.12.0) lib/grape/middleware/formatter.rb:34:in `block in after'
  grape (0.12.0) lib/grape/middleware/formatter.rb:33:in `collect'
  grape (0.12.0) lib/grape/middleware/formatter.rb:33:in `after'
  grape (0.12.0) lib/grape/middleware/base.rb:25:in `call!'
  grape (0.12.0) lib/grape/middleware/base.rb:18:in `call'
  grape (0.12.0) lib/grape/middleware/error.rb:27:in `block in call!'
  grape (0.12.0) lib/grape/middleware/error.rb:26:in `catch'
  grape (0.12.0) lib/grape/middleware/error.rb:26:in `call!'
  grape (0.12.0) lib/grape/middleware/base.rb:18:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  grape (0.12.0) lib/grape/endpoint.rb:196:in `call!'
  grape (0.12.0) lib/grape/endpoint.rb:184:in `call'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:152:in `block in call'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:96:in `block in recognize'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:75:in `optimized_each'
  rack-mount (0.8.3) lib/rack/mount/code_generation.rb:95:in `recognize'
  rack-mount (0.8.3) lib/rack/mount/route_set.rb:141:in `call'
  grape (0.12.0) lib/grape/api.rb:98:in `call'
  grape (0.12.0) lib/grape/api.rb:33:in `call!'
  grape (0.12.0) lib/grape/api.rb:29:in `call'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/middlewares/params_decoder_middleware.rb:19:in `call'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/middlewares/logger_middleware.rb:12:in `call'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/middlewares/locale_middleware.rb:21:in `block in call'
  custom_fields (2.4.0.rc5) lib/custom_fields/extensions/mongoid/fields/i18n.rb:50:in `with_locale'
  locomotivecms (3.0.0.pre.beta.1) app/api/locomotive/api/middlewares/locale_middleware.rb:20:in `call'
  rack (1.6.4) lib/rack/builder.rb:153:in `call'
  actionpack (4.2.4) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.4) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.4) lib/action_dispatch/routing/route_set.rb:821:in `call'
  locomotivecms (3.0.0.pre.beta.1) lib/locomotive/middlewares/site.rb:12:in `call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.4) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.4) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.4) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.4) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.4) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.4) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.4) lib/rails/engine.rb:518:in `call'
  railties (4.2.4) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/rryter/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  /Users/rryter/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  /Users/rryter/.rbenv/versions/2.2.1/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'
```

Since the error pops up when pushing with wagon, I am opening the issue here.

**Comment by rryter** [comment]
Some more info to reproduce this:
When the locales are set like this in the site.yml `locales: [en, fr, it, de]` it works. If you rearrange those in the back office or directly in the site.yml, like this: `locales: [de, fr, it, en]` then the error occurs.

**Comment by did** [comment]
we've got now warnings if the locales don't match. More than that, it stops pushing if both default locales in Wagon and Engine are not the same.
Thanks @rryter
