### ISSUE TITLE
Unable to read the local LocomotiveCMS site. Please check the logs.

### ISSUE THREAD

**Issue by Ben-Hadfield** [locomotivecms/wagon#262]
Hi!

I have been following the build a blog tutorial and adding a few additional content types other than posts but when I run `bundle exec wagon serve` I am now getting an error as follows; `Unable to read the local LocomotiveCMS site. Please check the logs.`

After checking the logs I have got stuck with the error log so hoping you could point me in the right direction regarding where I should look to solve this issue. Full error as follows:

```(<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 5 column 1
	/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse'
	/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:370:in `parse_stream'
	/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:318:in `parse'
	/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/psych.rb:245:in `load'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/utils/yaml_front_matters_template.rb:32:in `fetch_attributes_and_raw_source'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/utils/yaml_front_matters_template.rb:14:in `initialize'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:132:in `new'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:132:in `set_attributes_from_header'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:87:in `block (2 levels) in fetch'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter.rb:99:in `with_locale'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:86:in `block in fetch'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:74:in `each'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:74:in `fetch'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/file_system/pages_reader.rb:20:in `read'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:76:in `block (2 levels) in build_mounting_point'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:73:in `each'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:73:in `block in build_mounting_point'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:70:in `tap'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:70:in `build_mounting_point'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_mounter-1.5.7/lib/locomotive/mounter/reader/runner.rb:29:in `run!'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-1.5.8/lib/locomotive/wagon.rb:262:in `require_mounter'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-1.5.8/lib/locomotive/wagon.rb:75:in `serve'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-1.5.8/lib/locomotive/wagon/cli.rb:272:in `serve'
	/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/usr/local/lib/ruby/gems/2.2.0/gems/locomotivecms_wagon-1.5.8/bin/wagon:12:in `<top (required)>'
	/usr/local/bin/wagon:23:in `load'
	/usr/local/bin/wagon:23:in `<main>'```

**Comment by did** [comment]
The YAML header of one of your page is not valid. Wagon v2 should provide more information about this kind of error.
