### ISSUE TITLE
Wagon/Coal cannot upload SVG files

### ISSUE THREAD

**Issue by allanbreyes** [locomotivecms/wagon#265]
I can't seem to upload SVG files... getting an `undefined method error starts_with? for nil:NilClass`  I think this had to do with the recent fix on engine w/ fonts vs. images for SVGs.  This is off of master on both engine and wagon.  Here's the stack trace for an SVG upload:

```
.../locomotivecms_coal-1.0.0.rc1/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
.../locomotivecms_coal-1.0.0.rc1/lib/locomotive/coal/resources/concerns/request.rb:11:in `post'
.../locomotivecms_coal-1.0.0.rc1/lib/locomotive/coal/resources/base.rb:25:in `create'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_theme_assets_command.rb:23:in `persist'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:32:in `block in _push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:28:in `each'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:28:in `_push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:23:in `block in _push_with_timezone'
.../activesupport-4.2.4/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:22:in `_push_with_timezone'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `block in push'
.../activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:45:in `instrument'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:14:in `push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:10:in `push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:44:in `block in push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:70:in `block in each_resource'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:63:in `each'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:63:in `each_resource'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:43:in `push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/commands/push_command.rb:29:in `push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon.rb:73:in `push'
.../wagon-7a3f8c24184d/lib/locomotive/wagon/cli.rb:313:in `deploy'
.../thor-0.19.1/lib/thor/command.rb:27:in `run'
.../thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
.../thor-0.19.1/lib/thor.rb:359:in `dispatch'
.../thor-0.19.1/lib/thor/base.rb:440:in `start'
.../wagon-7a3f8c24184d/bin/wagon:12:in `<top (required)>'
.../bin/wagon:23:in `load'
.../bin/wagon:23:in `<main>'

```

**Comment by allanbreyes** [comment]
I am not a smart person.

SVG was under `images` instead of `samples`
