### ISSUE TITLE
'with_scope' & date range

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/wagon#284]
I would like to filter posts grouped by month to generate some statistics like that:
```
 * December 2015 (11)
 * November 2015 (4)
 * October 2015 (3)
 * September 2015 (2)
 * August 2015 (1)
```

I use `with_scope` to filter posts from specific month like that:
```
{% assign date_a = "2015-11-01" %}
{% assign date_b = "2015-12-01" %}
{% with_scope publish_at.gte: date_a, publish_at.lt: date_b %}
  <li><a href="/">December</a>&nbsp;({{ contents.posts.all.size }})</li>
{% endwith_scope %}
```

I get error `comparison of Date with String failed`:
```
Arrrghhhh, we could not render page

comparison of Date with String failed

File: ?

Code

No code

Back trace

/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/condition.rb:32:in `>='
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/condition.rb:32:in `matches?'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:94:in `block (2 levels) in filtered'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:93:in `each'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:93:in `block in filtered'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:90:in `each'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:90:in `find_all'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:90:in `filtered'
/home/adam/.rvm/gems/ruby-2.1.1/bundler/gems/steam-dc2a571fe418/lib/locomotive/steam/adapters/memory/query.rb:68:in `all'
...
```

How to do that corectly?

**Comment by adam-pl** [comment]
I've found new filter called `parse_date` in file `/home/[user]/.rvm/gems/ruby-2.2.3/bundler/gems/steam-09c6899f1043/lib/locomotive/steam/liquid/filters/date.rb`.

So now I can define date variable as Date type:
```
{% assign date_a = "2015-11-01" | parse_date: '%Y-%m-%d' %}
{% assign date_b = "2015-12-01" | parse_date: '%Y-%m-%d' %}
```

Now I can filter posts by a date range.

Documentation https://locomotive-v3.readme.io/docs/filters doesn't mention about ` parse_date` & `parse_date_time` filters.

**Comment by did** [comment]
thanks @adam-pl. Documentation updated. https://locomotive-v3.readme.io/v1.0/docs/filters#parse_date
