### ISSUE TITLE
Deploying empty site on stock install after sync

### ISSUE THREAD

**Issue by aeberlin** [locomotivecms/wagon#287]
Steps to reproduce:

1. Create blank site
2. Setup deploy yml for development.
3. Create `{app/content_types/,app/views/pages,data/}` and touch `.empty_directory` in each.
4. Sync to fetch default index and 404 liquid pages.
5. Try development deploy.

Fails in `PushSiteCommand#label_for`, where `decorated_entity` does not have a method `name`.

Can provide more info if needed. Cheers.

**Comment by did** [comment]
@aeberlin 

1/ How did you create your blank site? From the back-office? 
3/ Why did you create those folders by hand? Why didn't you use Wagon init or Wagon clone if the site was created from the back-office?
4/ How did you sync?

One last question, could you deploy with the "-v" option and give me the logs?

thanks!

**Comment by aeberlin** [comment]
Hi @did,

1. I created the blank site from the front-end after a fresh install and creating a new admin user via the rake task.
2. I created the folders by hand. I previously used the older version of locomotive a few years ago, and had been used to using the CMS admin interface to do everything. It was only after I had issues with `sync` and `deploy` that I dug deeper and found I needed those folders available.
3. `bundle exec wagon auth ... ...` and `bundle exec wagon sync development`

Here is the log:

```
$ be wagon deploy -v development

Pushing Site
 [failed]
    undefined method `name' for module `Kernel'
undefined method `name' for module `Kernel'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_site_command.rb:30:in `label_for'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:33:in `block in _push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/Users/foo/.gem/ruby/2.2.4/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/Users/foo/.gem/ruby/2.2.4/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:47:in `instrument'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:54:in `block in _push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:82:in `block in each_resource'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:75:in `each'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:75:in `each_resource'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:53:in `_push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:40:in `push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/commands/push_command.rb:30:in `push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon.rb:73:in `push'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/lib/locomotive/wagon/cli.rb:313:in `deploy'
	/Users/foo/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/foo/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/foo/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/foo/.gem/ruby/2.2.4/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/foo/.gem/ruby/2.2.4/gems/locomotivecms_wagon-2.0.0.rc6/bin/wagon:12:in `<top (required)>'
	/Users/foo/.gem/ruby/2.2.4/bin/wagon:23:in `load'
	/Users/foo/.gem/ruby/2.2.4/bin/wagon:23:in `<main>'
```

Thanks! Happy new year!

Cheers

**Comment by aeberlin** [comment]
After initializing via `bundle exec wagon init ...`, the issue seems to be cleared up.

I guess this issue can be closed, seems like it had something to do with `site.yml` and `translations.yml` missing from the `config/` directory. Sorry to bother you guys.
