### ISSUE TITLE
pushing error ("\xE6" on US-ASCII)

### ISSUE THREAD

**Issue by N00D13** [locomotivecms/wagon#303]
When i push my site i got these error 
```
"\xE6" on US-ASCII
```
or 
```
invalid byte sequence in US-ASCII
```

**Comment by did** [comment]
hey @N00D13, could you provide me more information? Stacktrace, context, versions, ...etc. Thanks!

**Comment by N00D13** [comment]
```
# Backtrace:

	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:36:in `replace_editable_elements'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:13:in `write_page'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:13:in `block (2 levels) in _pull'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `each'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `block in _pull'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `each'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `_pull'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:26:in `block in sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_base_command.rb:29:in `instrument'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:24:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:18:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:46:in `block in _sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:58:in `block in each_resource'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each_resource'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:45:in `_sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:32:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:26:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:97:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:332:in `sync'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/bin/wagon:23:in `load'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/bin/wagon:23:in `<main>'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	/Users/alexwellnitz/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by DanWebb** [comment]
Hi @did Also receiving this error while trying to sync a site i.e. `bundle exec wagon sync production -v` running `locale` gives.

```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=C
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Looking in config/site.yml and it contains a property like `locales: [en]` not sure if modifying this would help anything?

Stacktrace is...
```
/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:36:in `replace_editable_elements'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:13:in `write_page'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:13:in `block (2 levels) in _pull'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `each'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `block in _pull'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `each'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `_pull'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:26:in `block in sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_base_command.rb:29:in `instrument'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:24:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:18:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:46:in `block in _sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:58:in `block in each_resource'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each_resource'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:45:in `_sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:32:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:26:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:97:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:332:in `sync'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/bin/wagon:23:in `load'
	/home/woolacombe/woolacombe_holiday_cottages/vendor/bundle/ruby/2.1.0/bin/wagon:23:in `<main>'
```

Thanks in advance for any help.

**Comment by did** [comment]
@DanWebb I've just released a new version of Wagon (2.2.0.rc3). Could you try it please and let me know if it fixes your issue? thanks!

**Comment by DanWebb** [comment]
@did Thanks, what gem source would I get rc3 from? I only see up to rc2 here https://rubygems.org/gems/locomotivecms_wagon/versions and getting the gem not found error.

**Comment by did** [comment]
I'm super sorry @DanWebb. I forgot to release the Wagon gem! You should be good now.

**Comment by DanWebb** [comment]
No problem, that's working now thanks very much @did !

**Comment by did** [comment]
@DanWebb that's great! thanks for having me posted!
