### ISSUE TITLE
Unable to pull/sync due to undefined method 'force_encoding' for hash datatype

### ISSUE THREAD

**Issue by maniksingh92-xx** [locomotivecms/wagon#305]
Hi,
I've ran into this issue multiple times. Performing a sync/pull from wagon results in this error:

```
Syncing Site

Syncing Pages

# Error description:
undefined method `force_encoding' for {"en"=>"false"}:Hash

# Backtrace:

    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/concerns/assets_concern.rb:19:in `replace_asset_urls'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:27:in `block in editable_elements_attributes'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `each'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `inject'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `editable_elements_attributes'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:12:in `write_page'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:13:in `block (2 levels) in _pull'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `each'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `block in _pull'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `each'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `_pull'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:26:in `block in sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_base_command.rb:29:in `instrument'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:24:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:18:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:46:in `block in _sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:58:in `block in each_resource'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each_resource'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:45:in `_sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:32:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:26:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:97:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:332:in `sync'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/bin/wagon:23:in `load'
    /home/username/.rvm/gems/ruby-2.3.0@locomotive/bin/wagon:23:in `<main>'

```

These are the versions of locomotive gems installed:
- locomotivecms-liquid (4.0.0)
- locomotivecms-solid (4.0.1)
- locomotivecms_coal (1.2.0)
- locomotivecms_common (0.2.0)
- locomotivecms_steam (1.1.1)
- locomotivecms_wagon (2.1.1)

As general as the potential cause of the issue could be, i've not myself been able to pinpoint why the issue occurs; apart from the reason that there isn't any method 'force_encoding' in the ruby lang for the Hash class.

EDIT: The issue occurs while syncing pages. `bundle exec wagon sync production -r content_entries -v` works fine. 

Thanks.

**Comment by Jedtek** [comment]
Hi,

I also have this issue when trying to get a certain site pulled down to local (in the first instance) on Wagon . All latest versions.

It stops me entirely from then working on that site. Other sites pull down and edit fine but it is the exact error as above. Using ruby 2.3.0p0 on OSX.

Thanks,
Jed.

**Comment by did** [comment]
hi @maniksingh92, what's in the code of your liquid pages? It seems odd to me to have an editable_element returning ````{"en"=>"false"}````. Which version of Engine are you running? Can I have access to your site?

**Comment by taher435** [comment]
I am still facing this issue.

```
$ wagon sync local -v
Syncing Site

Syncing Pages

# Error description:
undefined method `force_encoding' for {"en"=>"false"}:Hash

# Backtrace:

        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/concerns/assets_concern.rb:19:in `replace_asset_urls'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:27:in `block in editable_elements_attributes'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `each'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `inject'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:26:in `editable_elements_attributes'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/sync_pages_command.rb:12:in `write_page'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:13:in `block (2 levels) in _pull'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `each'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:11:in `block in _pull'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `each'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_pages_command.rb:10:in `_pull'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:26:in `block in sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_sub_commands/pull_base_command.rb:29:in `instrument'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:24:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_sub_commands/concerns/base_concern.rb:18:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:46:in `block in _sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:58:in `block in each_resource'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:53:in `each_resource'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:45:in `_sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:32:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/sync_command.rb:26:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:97:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:332:in `sync'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/bin/wagon:23:in `load'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/bin/wagon:23:in `<main>'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/bin/ruby_executable_hooks:15:in `eval'
        /Users/maverick/.rvm/gems/ruby-2.3.0@locomotive/bin/ruby_executable_hooks:15:in `<main>'
```

Wagon version is `2.1.1`

**Comment by taher435** [comment]
@did this issue is been haunting us for quite some time and because of that we are no longer able to push code changes to production as without sync we would be over writing the production entries. Any idea how this can be fixed ASAP? I am ready to get on a paid consultation where we get on a call and you can take control of my system and debug?

**Comment by taher435** [comment]
Some more information from the logs on the engine

```
Started GET "/locomotive/api/v3/pages.json?auth_token=XXXXXXXXXXXXX" for ::1 at 2016-10-17 16:53:03 +0800
[LocomotiveCMS] [fetch site] host = localhost / site_handle = "production-v2" / locale = :en
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"handle"=>"production-v2"}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.001145s
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"email"=>"info@example.com", "authentication_token"=>"XXXXXXXXXXXXX"}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.000557s
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_accounts", "filter"=>{"_id"=>BSON::ObjectId('56cd29c04cb2070edd0fa7bd')}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.000801s
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_pages", "filter"=>{"site_id"=>BSON::ObjectId('577b359d4cb20714a345071d')}, "sort"=>{"position"=>1}}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.046701s
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_sites", "filter"=>{"_id"=>BSON::ObjectId('577b359d4cb20714a345071d')}, "limit"=>1, "singleBatch"=>true}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.000594s
MONGODB | localhost:27017 | engine_production.find | STARTED | {"find"=>"locomotive_content_types", "filter"=>{"site_id"=>BSON::ObjectId('577b359d4cb20714a345071d'), "_id"=>BSON::ObjectId('577b365c4cb20714a3450741')}}
MONGODB | localhost:27017 | engine_production.find | SUCCEEDED | 0.000684s
service="api.request" method="GET" endpoint="/v3/pages.json" params="{"auth_token"=>"XXXXXXXXXXXXX"}" headers="{"HTTP_X_LOCOMOTIVE_ACCOUNT_EMAIL"=>"info@example.com", "HTTP_X_LOCOMOTIVE_ACCOUNT_TOKEN"=>"XXXXXXXXXXXXX", "HTTP_X_LOCOMOTIVE_SITE_HANDLE"=>"production-v2", "HTTP_X_LOCOMOTIVE_LOCALE"=>"en"}" status="200" timestamp="2016-10-17 08:53:03 UTC"
```

**Comment by did** [comment]
I believe this issue has been solved in the last commits
