### ISSUE TITLE
/sample/ regex needs to be more robust

### ISSUE THREAD

**Issue by jiexi** [locomotivecms/wagon#312]
It seems wagon incorrectly parses occurrences of `/sample/` in the href of a link and attempts to check if the local content for that path exists. This is fine normally, but when links to external websites include `/sample/`, wagon will still check to see if local content exists, which will probably not actually exist. Or maybe i'm wrong and it's something else.

example data:
```
- Title of post:
    _slug: slug-of-post
    posted_at: 09/11/2014 00:00
    categories:
    - tech
    body: "<a style=\"line-height:
      1.5em;\" href=\"http://website.tld/samples/external_url\">http://website.tld/samples/external_url</a>"
```

After running wagon push:
```
...
    persisting Posts / Title of Post [failed]
    No such file or directory @ rb_sysopen - /Users/jiexi/Projects/xxx/public/samples/external_url">http://website.tld

# Error description:
No such file or directory @ rb_sysopen - /Users/jiexi/Projects/xxx/public/samples/external_url">http://website.tld

# Backtrace:

	/usr/local/lib/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize'
	/usr/local/lib/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `open'
	/usr/local/lib/ruby/gems/2.3.0/gems/multipart-post-2.0.0/lib/composite_io.rb:85:in `initialize'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_coal-1.2.0/lib/locomotive/coal/upload_io.rb:6:in `initialize'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/content_asset_decorator.rb:13:in `new'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/content_asset_decorator.rb:13:in `source'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:10:in `public_send'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:10:in `block (2 levels) in to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:9:in `each'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:9:in `block in to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:8:in `tap'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:8:in `to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_assets_command.rb:19:in `persist'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/persist_assets_concern.rb:11:in `block in replace_with_content_assets!'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/persist_assets_concern.rb:10:in `gsub'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/persist_assets_concern.rb:10:in `replace_with_content_assets!'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/content_entry_decorator.rb:39:in `decorate_text_field'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/content_entry_decorator.rb:32:in `method_missing'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:10:in `public_send'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:10:in `block (2 levels) in to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:9:in `each'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:9:in `block in to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:8:in `tap'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/concerns/to_hash_concern.rb:8:in `to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/decorators/content_entry_decorator.rb:59:in `to_hash'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:36:in `persist'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:12:in `block in _push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `each'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_content_entries_command.rb:10:in `_push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/usr/local/lib/ruby/gems/2.3.0/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:73:in `push'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/usr/local/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/usr/local/lib/ruby/gems/2.3.0/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/usr/local/bin/wagon:23:in `load'
	/usr/local/bin/wagon:23:in `<main>'

```

**Comment by did** [comment]
thanks @jiexi for the bug report!
