### ISSUE TITLE
Wagon Clone Error

### ISSUE THREAD

**Issue by stunjiturner** [locomotivecms/wagon#322]
```

/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::BASE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ALL
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_NaN
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_INFINITY
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_UNDERFLOW
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_OVERFLOW
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::EXCEPTION_ZERODIVIDE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_MODE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_UP
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_DOWN
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_UP
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_DOWN
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_CEILING
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_FLOOR
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::ROUND_HALF_EVEN
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NaN
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_ZERO
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_ZERO
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_FINITE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_FINITE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_POSITIVE_INFINITE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::SIGN_NEGATIVE_INFINITE
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::INFINITY
/Users/sturner/.gem/ruby/2.2.2/extensions/x86_64-darwin-14/2.2.0-static/bigdecimal-1.2.7/bigdecimal.bundle: warning: already initialized constant BigDecimal::NAN
       exist  blc
   identical  blc/Gemfile
   identical  blc/Guardfile
       exist  blc/app/content_types
       exist  blc/app/views/pages
       exist  blc/app/views/snippets
   identical  blc/config/deploy.yml
       exist  blc/data
       exist  blc/public/fonts
       exist  blc/public/images
       exist  blc/public/javascripts
       exist  blc/public/samples
       exist  blc/public/stylesheets

# Error description:
uninitialized constant Psych::TreeBuilder

# Backtrace:

	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/tools/styled_yaml.rb:53:in `<module:StyledYAML>'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/tools/styled_yaml.rb:19:in `<top (required)>'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_command.rb:3:in `require_relative'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/pull_command.rb:3:in `<top (required)>'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:84:in `require_relative'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:84:in `pull'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:30:in `pull_site'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:14:in `clone'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/commands/clone_command.rb:6:in `clone'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon.rb:109:in `clone'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/lib/locomotive/wagon/cli.rb:236:in `backup'
	/Users/sturner/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	/Users/sturner/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/sturner/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	/Users/sturner/.gem/ruby/2.2.2/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	/Users/sturner/.gem/ruby/2.2.2/gems/locomotivecms_wagon-2.1.1/bin/wagon:12:in `<top (required)>'
	/Users/sturner/.gem/ruby/2.2.2/bin/wagon:23:in `load'
	/Users/sturner/.gem/ruby/2.2.2/bin/wagon:23:in `<main>'```

**Comment by did** [comment]
@stunjiturner ```gem update --system```` maybe?

**Comment by stunjiturner** [comment]
I will try it!

S. Tunji Turner
sightuary

**Comment by stunjiturner** [comment]
worked

**Comment by did** [comment]
great! 👍
