### ISSUE TITLE
Resource invalid in metafields_schema

### ISSUE THREAD

**Issue by ArthurJahn** [locomotivecms/wagon#345]
Defining new properties in `metafields_schema.yml` causes wagon to do not deploy anymore.
the file looks like this
```yml
smtp:
  label: Email service
  fields:
    host:
      type: string
    user:
      type: string
    password:
      type: string
```
The error output follows:
```
root@stretch:/vagrant# wagon deploy production -v

Pushing Site
  persisting Alvim Consultoria [failed]
    Resource invalid: metafields_schema The property '#/0/fields/0/position' of type String did not match the following type: integer
Resource invalid: metafields_schema The property '#/0/fields/0/position' of type String did not match the following type: integer
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/concerns/request.rb:36:in `do_request'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_coal-1.0.0/lib/locomotive/coal/resources/current_site.rb:13:in `update'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_site_command.rb:25:in `persist'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
        /usr/local/rvm/gems/ruby-2.2.9/gems/activesupport-4.2.10/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:47:in `instrument'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon.rb:73:in `push'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/lib/locomotive/wagon/cli.rb:308:in `deploy'
        /usr/local/rvm/gems/ruby-2.2.9/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        /usr/local/rvm/gems/ruby-2.2.9/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        /usr/local/rvm/gems/ruby-2.2.9/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        /usr/local/rvm/gems/ruby-2.2.9/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        /usr/local/rvm/gems/ruby-2.2.9/gems/locomotivecms_wagon-2.0.1/bin/wagon:12:in `<top (required)>'
        /usr/local/rvm/gems/ruby-2.2.9/bin/wagon:23:in `load'
        /usr/local/rvm/gems/ruby-2.2.9/bin/wagon:23:in `<main>'
        /usr/local/rvm/gems/ruby-2.2.9/bin/ruby_executable_hooks:15:in `eval'
        /usr/local/rvm/gems/ruby-2.2.9/bin/ruby_executable_hooks:15:in `<main>'
```
I don't know if it's really an issue or just something i'm missing. Please give me a hand.

**Comment by meesern** [comment]
I have the same error attempting to deploy a clean blog site based on locomotivecms/site-templates (no changes to the metafields_schema or template).  

It's not clear where the error comes from or what it means so it's difficult to fix.

**Comment by meesern** [comment]
I get the same/similar error when following the quick start guide here: https://doc.locomotivecms.com/docs.  Deploying to https://station.locomotive.works.  Can't get a site deployed at all! 

When deploying from the quickstart guide I get the error `Resource invalid: metafields_schema Invalid metafields_schema: "822: unexpected token at ''". Check it out on http://jsonlint.com`

**Comment by more-ron** [comment]
Having the same issue. @ArthurJahn did you find a solution?

**Comment by more-ron** [comment]
I've followed the stack trace. It doesn't look `position` is being converted to string. However, the request is using url encoded form data which would pass all values as string.

![1__heroku_logs_--tail__node_](https://user-images.githubusercontent.com/194198/52999927-ef783e00-33db-11e9-94cf-b3f0e2cf6091.png)

I wonder if Locomotive could use JSON payloads instead.

**Comment by meesern** [comment]
As far as I can see the problem is as @more-ron  shows - during the Wagon deploy the `metafield-schema` is being passed to Engine within the parameters of an API call. 

The error message comes from Engine's API parameter checking via Grape's parameter validation.  

It seems as though the problem is Wagon is passing the metafield-schema 'position' as a string but Engine is expecting an integer.

With that I am no nearer to understanding how to fix it.

**Comment by more-ron** [comment]
I believe there's at least two ways to solve this issue. Wagon needs to use JSON payload instead of URL encoded form payload. That way the integer is maintained since JSON could encode integers. Or on the engine side, convert the integer expressed as string back to integer via some middleware.

I would try and make a PR for this when I get the time unless someone beat me to it.

**Comment by more-ron** [comment]
Hmmm... I was trying out fixing this on `Locomotive::Coal::Resources` level as it seems possible to just  use JSON payload and maintain the integer datatype from there. However, since an image file is also part of the payload, I quickly found out that it's not an option.

The other option that I'm considering is intercepting it on the server side and converting it back to integer.

Another option is to loosen the restriction on Grape.

**Comment by did** [comment]
I can't reproduce the bug with the latest commits of Steam + Wagon. 
Sorry people for my delayed answer :-(

**Comment by ArthurJahn** [comment]
I believe this is not closed yet. I've updated my Wagon and the error persists.

**Comment by did** [comment]
hey @ArthurJahn! What's inside your Wagon Gemfile? thanks!

**Comment by did** [comment]
For my tests, I used the same `metafields_schema.yml` as you posted at the beginning of this thread. I also deployed it with the last version of Wagon (3.0.0.rc0) and it worked.
