### ISSUE TITLE
Trouble pushing to production - undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by justmark** [locomotivecms/wagon#346]
Am running:

Wagon: 2.4.0.rc2
Locomotive: 3.3.0

I've had a site running for some time.  Am now getting an error when trying to push to production:

```
  persisting company (en) [done]
 [failed]
    undefined method `+' for nil:NilClass

# Error description:
undefined method `+' for nil:NilClass

# Backtrace:

	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:40:in `label_for'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:33:in `block in _push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.6/lib/active_support/core_ext/time/zones.rb:64:in `use_zone'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.6/lib/active_support/notifications.rb:168:in `instrument'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:55:in `block in _push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:84:in `block in each_resource'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:77:in `each'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:77:in `each_resource'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:54:in `_push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:41:in `push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon.rb:73:in `push'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/cli.rb:318:in `deploy'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/home/justmark/.rvm/gems/ruby-2.2.5/gems/locomotivecms_wagon-2.4.0.rc2/bin/wagon:12:in `<top (required)>'
	/home/justmark/.rvm/gems/ruby-2.2.5/bin/wagon:23:in `load'
	/home/justmark/.rvm/gems/ruby-2.2.5/bin/wagon:23:in `<main>'
	/home/justmark/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
	/home/justmark/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'
```

Any thoughts on how to narrow this down to find the culprit ?

**Comment by truthSeekr** [comment]
I have same problem using
gem 'locomotivecms_wagon', '~> 2.4.0'
gem 'locomotivecms', :git => "https://github.com/locomotivecms/engine.git", :branch => "v3.4.x"

I push to local. Di you resolve this ?

**Comment by fusco** [comment]
**Starting stack** : 

- locomotive-wagon : 3.0.5
- locomotivecms 4.0.3
- rails 5.2.4.2 
- ruby 2.7.0
- MacOS Catalina

**I have resolve this issue with** : 

- downgrading ruby  2.7.0 -> 2.6.4
- installing imagemagick with brew
