### ISSUE TITLE
Cloning a locomotive site gives "wrong number of arguments" Error

### ISSUE THREAD

**Issue by toreyheinz** [locomotivecms/wagon#347]
```shell
Pulling Site

# Error description:
wrong number of arguments (given 2, expected 3)

# Backtrace:

	/Users/th/.rubies/ruby-2.5.1/lib/ruby/2.5.0/psych/visitors/yaml_tree.rb:56:in `initialize'
	/Users/th/.gem/ruby/2.5.1/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/tools/styled_yaml.rb:108:in `new'
	/Users/th/.gem/ruby/2.5.1/gems/locomotivecms_wagon-2.4.0.rc2/lib/locomotive/wagon/tools/styled_yaml.rb:108:in `dump'
```
https://github.com/ruby/psych/blob/c2e3a035b101a3537706e244bc5834a6e423f3cc/lib/psych/visitors/yaml_tree.rb#L49-L56
``` ruby
      def self.create options = {}, emitter = nil
        emitter      ||= TreeBuilder.new
        class_loader = ClassLoader.new
        ss           = ScalarScanner.new class_loader
        new(emitter, ss, options)
      end


      def initialize emitter, ss, options
```
https://github.com/locomotivecms/wagon/blob/dba61ccf686cf6c9ae753b3ed204691ebe41fb7a/lib/locomotive/wagon/tools/styled_yaml.rb#L108

Changing that line to `visitor = YAMLTree.create(options, TreeBuilder.new)` fixed it for me.

Based on the history I'm not sure if it would have ever worked, but I also don't know if I've ever tried it.

**Comment by did** [comment]
Fixed. thanks!
