### ISSUE TITLE
Can't add a new key into hash during iteration

### ISSUE THREAD

**Issue by DonKoko** [locomotivecms/wagon#356]
I have a page that is with json response and I keep on getting this error which leads to the wagon server crashing:
```
Started GET "/sapi/main_menu_items.json" at 2019-02-22 17:53:31 +0100
  Params: {}
  Timezone: UTC
  Locale used: EN
  Found page "Main menu items" [sapi/main_menu_items]

# Error description:
can't add a new key into hash during iteration

# Backtrace:

	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/backends/base.rb:162:in `initialize_connection'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:1527:in `event_callback'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run_machine'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/eventmachine-1.2.7/lib/eventmachine.rb:195:in `run'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.beta1/lib/locomotive/wagon/commands/serve_command.rb:42:in `start'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.beta1/lib/locomotive/wagon/commands/serve_command.rb:13:in `start'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.beta1/lib/locomotive/wagon.rb:40:in `serve'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.beta1/lib/locomotive/wagon/cli.rb:300:in `serve'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/gems/locomotivecms_wagon-3.0.0.beta1/bin/wagon:12:in `<top (required)>'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/bin/wagon:23:in `load'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/bin/wagon:23:in `<main>'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	/Users/donkoko/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
```

Here is how the page looks:
```
---
title: Main menu items
slug: main_menu_items
handle: main_menu_items
position: 99
listed: false
published: true
is_layout: false
response_type: application/json
---

{% with_scope listed: true, published: true %}
{
    "links": [
      {% for page in site.pages %}
        {
          {% include 'json_parser', key: 'slug', value: page.slug %},
          {% include 'json_parser', key: 'title', value: page.title %}
        }{% unless forloop.last %},{% endunless %}
      {% endfor %}
    ]
}
{% endwith_scope %}
```
but this doesnt only happen with this page. Happens with a almost every json page i have.

Wagon version:
`gem 'locomotivecms_wagon', '~> 3.0.0.beta1'`

**Comment by did** [comment]
Hmm, I also have the same issue with one of our client sites. Looks like Thin is not able to both render a page and calls an internal API endpoint I'm wondering if Puma would solve this issue.

**Comment by DonKoko** [comment]
For me it happens only in wagon, so I am not sure how the wagon server runs on the backend. Also something i noticed is that it happens if I very quickly make the request 2 times in a row. So if i click refresh 2 times really quick, server crashes. Don't know if that info helps.

**Comment by did** [comment]
this is the exact same issue I saw on my side!
