### ISSUE TITLE
undefined method `start' for nil:NilClass

### ISSUE THREAD

**Issue by manuchap** [locomotivecms/wagon#369]
When quitting wagon (invoked with the -v option) it throws this error:
```shell
^C
# Error description:
undefined method `start' for nil:NilClass

# Backtrace:

	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/commands/serve_command.rb:42:in `start'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/commands/serve_command.rb:13:in `start'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon.rb:40:in `serve'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/cli.rb:318:in `serve'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/Users/manuchap/Sites/Loco/wagon/bin/wagon:12:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bin/wagon:23:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bin/wagon:23:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
```  
  
Also, if it's related, live reload only works with assets in the assets folder even though the service is invoked on other changes:

```shell
service=listen action=reload resource=pages timestamp=2019-05-26 16:39:44 +0200
service=listen action=reload resource=snippets timestamp=2019-05-26 16:39:44 +0200
service=listen action=reload resource=sections timestamp=2019-05-26 16:39:44 +0200
service=listen action=reload resource=pages timestamp=2019-05-26 16:40:13 +0200
service=listen action=reload resource=snippets timestamp=2019-05-26 16:40:13 +0200
service=listen action=reload resource=sections timestamp=2019-05-26 16:40:13 +0200
service=listen action=reload resource=site timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=content_types timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=pages timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=snippets timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=sections timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=content_entries timestamp=2019-05-26 16:41:35 +0200
service=listen action=reload resource=translations timestamp=2019-05-26 16:41:35 +0200
```
Versions:
```
locomotivecms_wagon (3.0.0.rc0)
locomotivecms_coal (1.6.0.rc1)
locomotivecms_common (0.3.1)
locomotivecms_steam (1.5.0.rc0)
```

**Comment by did** [comment]
@manuchap are u using the last commit of Wagon?

**Comment by manuchap** [comment]
Yes. I checkout wagon, common, coal and steam first thing every day and use their cloned version.

**Comment by manuchap** [comment]
I deamonized mode I have this error:
```shell
log writing failed. closed stream
^C
# Error description:
undefined method `log_file=' for nil:NilClass

# Backtrace:

	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/commands/serve_command.rb:104:in `daemonize'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/commands/serve_command.rb:28:in `start'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/commands/serve_command.rb:13:in `start'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon.rb:40:in `serve'
	/Users/manuchap/Sites/Loco/wagon/lib/locomotive/wagon/cli.rb:318:in `serve'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	/Users/manuchap/Sites/Loco/wagon/bin/wagon:12:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bin/wagon:23:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bin/wagon:23:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
	/Users/manuchap/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
	/Users/manuchap/.rbenv/versions/2.5.3/bin/bundle:23:in `load'
	/Users/manuchap/.rbenv/versions/2.5.3/bin/bundle:23:in `<main>'
```
