### ISSUE TITLE
'delete [environment] content_type [slug]' fails under Windows 10

### ISSUE THREAD

**Issue by greyskin** [locomotivecms/wagon#388]
If I run `wagon delete [environment] content_type [slug]` (content_type singular [as per the documentation](https://doc.locomotivecms.com/docs/delete-resources)), I receive the following error message:

```
Are you sure? [yes, no] yes
C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/concerns/deploy_file_concern.rb:23:in `rescue in read_deploy_settings': Unable to read the config/deploy.yml file (No such file or directory @ rb_sysopen - -v/config/deploy.yml) (RuntimeError)
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/concerns/deploy_file_concern.rb:15:in `read_deploy_settings'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/concerns/api_concern.rb:48:in `connection_information_from_env_and_path'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/delete_command.rb:73:in `client'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/delete_command.rb:49:in `delete_single'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/delete_command.rb:28:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/commands/delete_command.rb:20:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon.rb:121:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/lib/locomotive/wagon/cli.rb:399:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bundler/gems/wagon-3fef025b049c/bin/wagon:12:in `<top (required)>'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bin/wagon:23:in `load'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bin/wagon:23:in `<main>'
```

I can run `wagon delete [environment] content_types` to delete all content types.

The only way I have found to delete a specific content_type from engine is as follows:
- run the above "delete all" command
- re-deploy all content_types (excluding the one I want deleted from engine - depending on the scenario, this could mean temporarily deleting the content_type locally prior to deployment)
- re-deploy all content_entries

I know that `wagon delete [environment] content_type [slug]` used to work, because I've used it many times and have my own list of wagon commands that I've tested and used.

**Comment by greyskin** [comment]
Actually scratch that: I cannot deploy only the remaining content_types with data.

If I run `bundle exec wagon deploy [environment] -r content_types -d` the content_types are deployed, but without data.

**Comment by greyskin** [comment]
Still getting this issue in 2022.

I'm using WSL (Windows Subsystem for Linux) these days.

**Gemfile for a project as follows:**
```
# By default, Wagon 3 doesn't need `bundle exec` to be executed.
# However, if down the road, you want to run a specific version of Wagon or try a new version
# without overriding the global Wagon binary, please use this Gemfile.

source 'https://rubygems.org'

gem 'locomotivecms_wagon', github: 'locomotivecms/wagon'

gem 'locomotivecms_steam', github: 'locomotivecms/steam', require: false

group :development do
  # Mac OS X
  gem 'rb-fsevent', '~> 0.10.0', require: 'rb-fsevent' if RUBY_PLATFORM.include?('darwin')

  # Unix
  gem 'therubyracer', require: 'v8', platforms: :ruby unless RUBY_PLATFORM.include?('darwin')

  gem 'rb-inotify', '~> 0.10.0', require: 'rb-inotify' if RUBY_PLATFORM.include?('linux')

  # Windows
  gem 'wdm', '~> 0.1.1', require: 'wdm' if RUBY_PLATFORM =~ /mswin|mingw/i
end

group :misc do
  # Add your extra gems here
  # gem 'susy', require: 'susy'
  # gem 'bourbon', require: 'bourbon'
  
  gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
  
end
```

**Error message:**
```
Are you sure? [yes, no] yes
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
/home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/faraday-0.17.5/lib/faraday/upload_io.rb:65: warning: constant ::UploadIO is deprecated
/home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/faraday-0.17.5/lib/faraday/upload_io.rb:66: warning: constant ::Parts is deprecated
Traceback (most recent call last):
        14: from /home/luke/.rbenv/versions/2.5.8/bin/wagon:23:in `<main>'
        13: from /home/luke/.rbenv/versions/2.5.8/bin/wagon:23:in `load'
        12: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/bin/wagon:73:in `<top (required)>'
        11: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        10: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
         9: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
         8: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         7: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/lib/locomotive/wagon/cli.rb:401:in `delete'
         6: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/lib/locomotive/wagon.rb:121:in `delete'
         5: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/lib/locomotive/wagon/commands/delete_command.rb:20:in `delete'
         4: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/lib/locomotive/wagon/commands/delete_command.rb:28:in `delete'
         3: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_wagon-3.1.0.beta1/lib/locomotive/wagon/commands/delete_command.rb:49:in `delete_single'
         2: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_coal-1.7.0/lib/locomotive/coal/resources/base.rb:40:in `destroy'
         1: from /home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_coal-1.7.0/lib/locomotive/coal/resources/concerns/request.rb:19:in `delete'
/home/luke/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/locomotivecms_coal-1.7.0/lib/locomotive/coal/resources/concerns/request.rb:54:in `do_request': Resource not found (Locomotive::Coal::UnknownResourceError)
```

**Comment by greyskin** [comment]
`wagon delete [env] content_type [content_type_slug]` appears to be working now in the current version of wagon. Closing this issue.
