### ISSUE TITLE
Deploying content_type_templates fails without error

### ISSUE THREAD

**Issue by greyskin** [locomotivecms/wagon#391]
When running `wagon deploy` on a content_type_template file, the file fails to deploy and no error is displayed.

**I have tried:**
- `bundle exec wagon deploy [env] -r pages -f some-folder/content_type_template -v` (which I believe is the correct syntax)

Response:
> "Pushing Pages
> Your site has been deployed."

- `bundle exec wagon deploy [env] -r page -f some-folder/content_type_template -v`

Response:
> Your site has been deployed."

**Also for the avoidance of doubt I have tried:**
- `bundle exec wagon deploy staging page campervans/content_type_template -v`

Response: (does actually get an error)
> ERROR: "wagon deploy" was called with arguments ["staging", "page", "campervans/content_type_template"]
Usage: "wagon deploy ENV [PATH]"

- `bundle exec wagon deploy staging -r page campervans/content_type_template -v`

Response:
> Your site has been deployed.

- `bundle exec wagon deploy staging -r pages campervans/content_type_template -v`

Response:
> Pushing Pages
> [pushes all pages]
> Your site has been deployed.

**Comment by greyskin** [comment]
Closed because this is not the issue described. The issue is instead either:
- a consistency issue across wagon commands OR
- a documentation issue

The [docs](https://doc.locomotivecms.com/docs/deploy) state with regard to the use of the `-f` extension:
> Filter the resource(s) to be deployed by its name **plus extension**. It can be used in conjunction with '-r' option to control exactly what is been pushed.
(emphasis mine)

The following command works to push content_type_templates:
- `bundle exec wagon deploy staging -r pages -f some-folder/content_type_template.liquid -v`

The reason I had failed to use the extension is because I had been using the delete command and had just been reading the [docs on deletion](https://doc.locomotivecms.com/docs/delete-resources), which do not include the file extension in the comand.

**Comment by greyskin** [comment]
Ok so it looks like it's 1) a consistency issue across wagon commands

When I want to delete a page with wagon, I must run:
`bundle exec wagon delete staging page [page-slug]` (**no -r extension**, **no -f extension**, **no file extension**)

Running the `delete` command with `-r` or `-f` extensions results in an error as expected:
> ERROR: "wagon delete" was called with arguments ["evn", "-r", "page", "-f", "page-slug", "-v"]
> Usage: "wagon delete ENV RESOURCE [SLUG] [PATH]"

But running the `delete` command with the file extension (as required for the `deploy` command) results in an unhelpful error:
> Are you sure? [yes, no]

yes
> C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/concerns/deploy_file_concern.rb:23:in `rescue in read_deploy_settings': Unable to read the config/deploy.yml file (No such file or directory @ rb_sysopen - -v/config/deploy.yml) (RuntimeError)
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/concerns/deploy_file_concern.rb:15:in `read_deploy_settings'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/concerns/api_concern.rb:49:in `connection_information_from_env_and_path'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/delete_command.rb:73:in `client'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/delete_command.rb:49:in `delete_single'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/delete_command.rb:28:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/delete_command.rb:20:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon.rb:121:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/cli.rb:401:in `delete'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/gems/locomotivecms_wagon-3.0.5/bin/wagon:73:in `<top (required)>'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bin/wagon:23:in `load'
        from C:/Dev/Dependencies/rubyinstaller-2.4.4-1-x64/lib/ruby/gems/2.4.0/bin/wagon:23:in `<main>'
