### ISSUE TITLE
Receiveing an error while deploying:  persisting index (en) [failed]

### ISSUE THREAD

**Issue by AVHoncharov** [locomotivecms/wagon#410]
Hello guys. I'm get stuck with deploying loco site. Syncing works, but not deploying. Please, point me out where and what could I missed. When I try to deploy, on pushing pages step receive an error:

 persisting index (en) [failed]
 Locomotive Back-office error. Contact your administrator or check your application logs.
# Error description:
Locomotive::Coal::ServerSideError

# Error description:
Locomotive::Coal::ServerSideError

# Backtrace:
        /var/lib/gems/2.7.0/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:54:in `do_request'
        /var/lib/gems/2.7.0/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/concerns/request.rb:15:in `put'
        /var/lib/gems/2.7.0/gems/locomotivecms_coal-1.6.0/lib/locomotive/coal/resources/base.rb:35:in `update_with_locale'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:27:in `block 
in persist'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:114:in `block (3 levels) in translated_in'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:113:in `tap' 
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:113:in `block (2 levels) in translated_in'
        /var/lib/gems/2.7.0/gems/locomotivecms_steam-1.5.3/lib/locomotive/steam/decorators/i18n_decorator.rb:48:in `__with_locale__'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:112:in `block in translated_in'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `each'        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `find_all'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:111:in `translated_in'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_pages_command.rb:23:in `persist'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:34:in `block in _push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `each'  
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:30:in `_push' 
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:25:in `block in _push_with_timezone'
        /var/lib/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:24:in `_push_with_timezone'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:18:in `block in push'
        /var/lib/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:170:in `instrument'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:50:in `instrument'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:16:in `push'  
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_sub_commands/push_base_command.rb:12:in `push'  
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:65:in `block in _push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:94:in `block in each_resource'       
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:87:in `each'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:87:in `each_resource'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:64:in `_push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:51:in `push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/commands/push_command.rb:31:in `push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon.rb:74:in `push'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/lib/locomotive/wagon/cli.rb:352:in `deploy'
        /var/lib/gems/2.7.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        /var/lib/gems/2.7.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        /var/lib/gems/2.7.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        /var/lib/gems/2.7.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        /var/lib/gems/2.7.0/gems/locomotivecms_wagon-3.0.5/bin/wagon:73:in `<top (required)>'
        /usr/local/bin/wagon:23:in `load'
        /usr/local/bin/wagon:23:in `<main>'

**Comment by greyskin** [comment]
If you go into the Back Office and navigate to Developers > Errors, are any errors listed?
